#!/usr/bin/env bash

set -u

splinter_dir="splinter"
splinter_zip="${splinter_dir}.zip"
splinter_archive="https://github.com/marcomc/splinter/archive/master.zip"
base_profile="base"
base_profile_example="base-example"

function shell_join {
  local arg
  printf "%s" "$1"
  shift
  for arg in "$@"; do
    printf " "
    printf "%s" "${arg// /\ }"
  done
}

function abort {
  printf "%s\n" "$1"
  exit 1
}

function execute {
  "$@" || abort "$(printf "Failed during: %s" "$(shell_join "$@")")"
}

if [ -d "${splinter_dir}" ];then
  echo "Removing existing directory '${splinter_dir}' if empty"
  execute "rmdir" "${splinter_dir}"
  # abort "$(printf "Failed directory %s already exists!" "$(shell_join "${splinter_dir}")")"
fi

temp_dir=$(mktemp -d)

echo "Downloading Splinter in to '${temp_dir}/${splinter_zip}'..."
execute "curl" "-H" "'Cache-Control: no-cache'" "-fsSL" "${splinter_archive}" "-o" "${temp_dir}/${splinter_zip}"

echo "Decompressing Splinter archive in to '${temp_dir}'..."
execute "unzip" "-qq" "${temp_dir}/${splinter_zip}" "-d" "${temp_dir}"
ls "${temp_dir}"

echo "Moving Splinter files to '${splinter_dir}'..."
execute "mkdir" "-p" "${splinter_dir}"
execute "mv" "${temp_dir}"/*/* "${splinter_dir}"

echo "Remove 'test' directory and files..."
[[ -d ${splinter_dir}/test ]] && execute "rm" "-rf" "${splinter_dir}/test"
[[ -f ${splinter_dir}/.travis.yml ]] && execute "rm" "${splinter_dir}/.travis.yml"
[[ -f ${splinter_dir}/.gitignore ]] && execute "rm" "${splinter_dir}/.gitignore"
[[ -f ${splinter_dir}/.gitmodules ]] && execute "rm" "${splinter_dir}/.gitmodules"

echo "Creating profile 'base'..."
execute "cp" "-a" "${splinter_dir}/profiles/${base_profile_example}" "${splinter_dir}/profiles/${base_profile}"

echo "Installing tools..."
(execute "${splinter_dir}/splinter" "update" "tools") 1> /dev/null || exit 1

echo "Removing temporary files..."
execute "rm" "-rf" "${temp_dir}"

echo "Installation successful! now go to './${splinter_dir}'"
